#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#rm -f constant/polyMesh/boundary
#rm -f constant/polyMesh/sets/*_old
#rm -rf constant/panelRegion/polyMesh
#rm -rf patch* 
rm -f log.* *.png
rm -rf logs *.data
#rm -f outFlameHeight*
#rm -rf VTK
#rm -rf HRR
#rm -fr fieldMinMax
#rm -fr postProcessing

# rm -r constant/!(polyMesh|*Constant)
# find constant/* -maxdepth 1 ! -name "*Constant" ! -name "polyMesh" -delete
# # rm -r system/fv{Schemes,Solution}
rm -rf system/fvSchemes system/fvSolution
# rm -r system/fv{Schemes,Solution}
# rm -r constant/!(polyMesh|*Constant)

# -----------------------------------------------------------------------------
