#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions # Source tutorial run functions

rm -f log.paraFoam
runApplication paraFoam -builtin &
# # # ----------------------------------------------------------------- end-of-file
